// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH_0s4GwNPf_EiMxXYTAJSirNKu7db8n0',
    appId: '1:383981160798:web:3d3f1e74c20adacdab27cf',
    messagingSenderId: '383981160798',
    projectId: 'finance-530c4',
    authDomain: 'finance-530c4.firebaseapp.com',
    storageBucket: 'finance-530c4.firebasestorage.app',
    measurementId: 'G-VFTKLZ717P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuWGmIX-gDcuSuvfE8uFpD5AoB1MECXP0',
    appId: '1:383981160798:android:8c0816834f53729cab27cf',
    messagingSenderId: '383981160798',
    projectId: 'finance-530c4',
    storageBucket: 'finance-530c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Ct4C1R09hCNR7KvOFthHmqGeWDHDxY4',
    appId: '1:383981160798:ios:3b71a59d6d507d92ab27cf',
    messagingSenderId: '383981160798',
    projectId: 'finance-530c4',
    storageBucket: 'finance-530c4.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );
}
